---
title: "Korning"
type: "challenge"
description: "Define a normalized database schema to store sales information and import it from a CSV file."
tags: "databases, sql, normalization"
visibility: "assign"
ignore:
- "korning.md"
- "sales.csv"
